wand-item:
  material: "BLAZE_ROD"
  name: "&6ChickenHunt Wand"

messages:
  prefix: "&e[ChickenHunt] &r"
  pos1_set: "&aPosition 1 set to: X: %x%, Y: %y%, Z: %z% (%world%)"
  pos2_set: "&aPosition 2 set to: X: %x%, Y: %y%, Z: %z% (%world%)"
  region_created: "&aRegion '%region%' created successfully!"
  region_deleted: "&aRegion '%region%' deleted."
  region_exists: "&cRegion '%region%' already exists."
  region_not_found: "&cRegion '%region%' not found."
  no_permission: "&cYou don't have permission to do that."
  player_only_command: "&cThis command can only be run by a player."
  wand_received: "&aYou have received the ChickenHunt Wand!"
  plugin_reloaded: "&aChickenHunt configuration and regions reloaded."
  wand_lore_pos1: "&7Left-click to set position 1"
  wand_lore_pos2: "&7Right-click to set position 2"
  setlobby_success: "&aLobby spawn berhasil diset!"
  lobby_spawn_not_set: "&cLobby spawn belum diset. Gunakan /ch setlobby di lokasi yang diinginkan."
  
  usage_create: "&cUsage: /ch create <regionName>" 
  usage_delete: "&cUsage: /ch delete <regionName>" 
  usage_start: "&cUsage: /ch start <regionName> [durationSeconds]"
  usage_stop: "&cUsage: /ch stop <regionName>"
  invalid_duration: "&cDuration must be a positive number."
  invalid_duration_format: "&cInvalid duration format. Please use numbers."
  game_already_started: "&cGame is already active in region '%region%'."
  game_started: "&aGame started in region '%region%'!"
  game_started_duration: "&aGame started in region '%region%' for %duration% seconds!"
  game_not_started: "&cGame is not active in region '%region%'."
  game_stopped_manual: "&aGame manually stopped in region '%region%'."
  game_ended_timed: "&eGame in region '%region%' has ended due to time limit."
  
  chicken_caught: "&a+1 Chicken!"
  chicken_cannot_damage: "&cYou cannot hurt this special chicken!"
  
  points_status: "&aYou have &e%points% &apoints from catching &e%chickens% &achickens!"
  
  # Admin points command messages
  usage_points: "&cUsage: /ch points [add|set|reset] <player> [amount]"
  usage_points_add: "&cUsage: /ch points add <player> <amount>"
  usage_points_set: "&cUsage: /ch points set <player> <amount>"
  invalid_number: "&cInvalid number. Please use a valid integer."
  invalid_points_action: "&cInvalid action. Use add, set, or reset."
  player_not_found: "&cPlayer '%player%' not found or not online."
  
  # Points admin feedback
  points_added_admin: "&aAdded &e%amount% &apoints to &e%player%&a. New total: &e%new_points%"
  points_added_player: "&aYou received &e%amount% &apoints from an admin. New total: &e%new_points%"
  points_set_admin: "&aSet &e%player%'s &apoints to &e%amount%"
  points_set_player: "&aAn admin set your points to &e%amount%"
  points_reset_admin: "&aReset &e%player%'s &apoints to 0"
  points_reset_player: "&cYour points have been reset to 0 by an admin"
  
  # Game countdown message
  game_countdown: "&aGame in region &e%region% &awill start in &e%seconds% &aseconds!"
  
  status_usage: "&cUsage: /ch status [regionName]"
  status_no_active_games: "&eThere are no active ChickenHunt games currently."
  status_header_all: "&6--- Active ChickenHunt Games Status ---"
  status_header_region: "&6--- Game Status in Region %region% ---"
  status_game_entry: "&e- Region: &f%region% &7(&f%time_left%&7)"
  status_game_entry_indefinite: "&e- Region: &f%region% &7(Indefinite Duration)"
  status_region_not_found_or_inactive: "&cRegion '%region%' not found or game is not active there."
  
  help_header_player: "&6--- ChickenHunt Player Commands ---"
  help_points: "&e/ch points &7- View your current points."
  help_status: "&e/ch status [region] &7- View game status."
  help_top: "&e/ch top [caught|points|money] &7- View leaderboards."
  help_join: "&e/ch join <region> &7- Join a lobby for the specified region."
  help_leave: "&e/ch leave &7- Leave your current lobby."
  help_lobby: "&e/ch lobby &7- View lobby status and available lobbies."
  help_forcejoin: "&e/ch forcejoin <player> <region> &7- Force a player to join a game."
  help_player_command: "&e/ch help &7- Show this help message."

  leaderboard_header: "&6--- Top Leaderboard: %type% ---"
  leaderboard_entry_caught: "&e#%rank%. &f%player% &7- &a%amount% chickens"
  leaderboard_entry_money: "&e#%rank%. &f%player% &7- &a%amount%"
  leaderboard_entry_points: "&e#%rank%. &f%player% &7- &a%amount% points"
  leaderboard_empty: "&eLeaderboard for %type% is still empty."
  usage_top: "&cUsage: /ch top [caught|points|money]"
  
  unknown_command: "&cUnknown command. Use /ch help."
  select_positions_first: "&cYou must select two positions with the wand first."
  positions_different_worlds: "&cBoth selection points must be in the same world."
  region_create_failed: "&cFailed to create region '%region%'. Ensure selection is valid."
  no_regions_yet: "&eNo regions have been created yet."
  region_list: "&6Available regions: &f%regions%"
  chicken_head_no_place: "&cThis special chicken head cannot be placed!"
  cooldown_active: "&cWait &f%seconds%s &cto catch again!"
  
  # Lobby Messages
  lobby_join_success: "&aSuccessfully joined lobby for region %region%!"
  lobby_join_failed: "&cFailed to join lobby! Lobby might be full or game is in progress."
  lobby_leave_success: "&aSuccessfully left the lobby!"
  lobby_leave_failed: "&cYou are not in a lobby!"
  lobby_not_in_lobby: "&cYou are not in a lobby!"
  lobby_already_in_lobby: "&cYou are already in a lobby! Type /ch leave to leave."
  lobby_countdown_started: "&eCountdown started! Game will begin in %seconds% seconds!"
  lobby_countdown_cancelled: "&cCountdown cancelled! Need at least %min_players% players."
  lobby_force_start_available: "&aForce start is now available! Type /ch forcestart to start the game now!"
  lobby_force_start_not_available: "&cForce start is not available! Wait 5 seconds after countdown starts."
  lobby_game_starting: "&aGame is starting! Have fun!"
  lobby_game_ended: "&eGame ended! Restoring players to original positions..."
  lobby_player_joined: "&a%player% joined the lobby! (%current%/%max%)"
  lobby_player_left: "&c%player% left the lobby! (%current%/%max%)"
  lobby_status: "&7Lobby Status: &f%players%/%max_players% &7- State: &f%state%"
  lobby_list_header: "&6--- Available Lobbies ---"
  lobby_list_entry: "&e%region% &7- &f%players%/%max_players% &7(%state%)"
  lobby_no_lobbies: "&eThere are no lobbies available."
  
  # Phase Messages
  phase_changed: "&6[Phase Change] &r%phase_name% &7- %phase_description%"
  phase_bossbar_title: "%phase_name% &8| &7Time: &f%time_left%s"
  speed_boost_activated: "&c&lSPEED BOOST! &e%player% &freached %catches% catches! Chickens are now faster!"
  speed_boost_ended: "&aSpeed boost ended! Chickens returned to normal speed."
  
  # Force Join Messages
  force_join_success: "&aForced %player% to join the game in region %region%!"
  force_join_failed: "&cFailed to force join %player%. They might already be in a game."
  force_join_target: "&eYou have been forced to join the ChickenHunt game in region %region%!"
  usage_forcejoin: "&cUsage: /ch forcejoin <player> <region>"

# Game Settings
game-settings:
  initial-chickens-per-region: 10  # Increased from 5 to raise baseline
  max-chickens-per-region: 120     # Increased to avoid early cap with higher spawn rate
  chicken-spawn-interval-seconds: 5 # Was 10; 300s / 5s = 60 waves per 5-minute match
  chickens-per-spawn-wave: 4       # Was 1; 60 waves * 4 + initial 10 ≈ 250 total potential spawns
  chicken-name: "&6Special Chicken" # Special chicken name
  catch-cooldown-seconds: 1.5  # Cooldown between chicken catches
  points-per-catch: 1 # Points earned for regular chicken catch
  countdown-seconds: 10 # Countdown before game starts
  display-scoreboard: true # Whether to display scoreboard during game
  default-duration-seconds: 300  # Default duration of 5 minutes if none specified

  # Lobby Settings
  lobby:
    min-players: 3              # Minimum players required to start
    max-players: 10             # Maximum players allowed in lobby
    countdown-seconds: 60       # Countdown duration before game starts
    force-start-delay: 5        # Seconds after countdown starts before force start is allowed
  
  # Phase System Settings
  phases:
    enabled: true
    phase-duration-seconds: 30  # Duration of each phase
    phases:
      - name: "&aCalm Phase"
        description: "&7Chickens are relaxed and easy to catch"
        chicken-speed-multiplier: 1.0
        spawn-rate-multiplier: 1.0
        bossbar-color: "GREEN"
      - name: "&eAlert Phase"
        description: "&7Chickens are getting nervous!"
        chicken-speed-multiplier: 1.3
        spawn-rate-multiplier: 1.2
        bossbar-color: "YELLOW"
      - name: "&cPanic Phase"
        description: "&7Chickens are panicking and moving fast!"
        chicken-speed-multiplier: 1.8
        spawn-rate-multiplier: 1.5
        bossbar-color: "RED"
      - name: "&5Chaos Phase"
        description: "&7Complete chaos! Chickens everywhere!"
        chicken-speed-multiplier: 2.2
        spawn-rate-multiplier: 2.0
        bossbar-color: "PURPLE"
  
  # Speed Boost Settings
  speed-boost:
    trigger-catches: 10         # When a player reaches this many catches
    speed-multiplier: 1.5       # How much faster chickens become
    duration-seconds: 60        # How long the speed boost lasts

  # Golden Chicken Settings
  golden-chicken:
    enabled: true
    name: "&eGolden Chicken"
    spawn-chance: 0.15
  # Extra poin di atas points-per-catch biasa (default 2)
  extra-points: 2
  # Kecepatan gerak golden chicken relatif terhadap chicken biasa (default 2.0)
  speed-multiplier: 2.0
  # (Deprecated) points-value masih didukung untuk kompatibilitas lama
  points-value: 2 # Legacy key (ignored jika extra-points ada)
  texture_value: "c414822a85c5e7073e207da133ce226859b0f74f238d584c3d3a42f223bb16bf"

# Item Kepala Ayam
chicken-head-item:
  material: "PLAYER_HEAD"
  name: "&6Special Chicken Head"
  lore:
    - "&7Right-click special chickens to catch them!"
    - "&7Earn points for the leaderboard!"
  # If material: PLAYER_HEAD, you can add a base64 texture value
  # Example: (This is a chicken head texture from Minecraft-Heads.com)
  texture_value: "c414822a85c5e7073e207da133ce226859b0f74f238d584c3d3a42f223bb16bf"

# Pesan terkait interaksi ayam
# (Bagian ini sudah digabungkan ke dalam messages di atas)
# Scoreboard Settings
scoreboard:
  title: "&6&lChicken Hunt &eEscadia"
  lines:
    - "&fRegion : &e%region%"
    - "&fTime Left : &e%time_left%"
    - ""
    - "&fYour Points : &a%points%"
    - "&fChicken Caught : &a%caught%"
    - ""
    - "&ePlay.escadia.id"
  update-interval-ticks: 20 # Update scoreboard every second

# Effect Settings
effects:
  catch_chicken:
    enabled: true
    sound:
      name: "ENTITY_CHICKEN_HURT"
      volume: 1.0
      pitch: 1.0
    particle:
      name: "SMOKE_NORMAL"
      count: 10
      offset_x: 0.2
      offset_y: 0.3
      offset_z: 0.2
      speed: 0.05
      # data: ""      # Data tambahan untuk partikel tertentu (misalnya REDSTONE: "255,0,0" untuk warna merah)

# Auto-scheduler Settings
auto-scheduler:
  enabled: true
  regions: ["hunt1", "hunt2"]  # List of regions to choose from randomly
  interval-minutes: 30         # Game starts every 30 minutes
  game-duration-minutes: 5     # Game duration of 5 minutes
  warning-seconds: 60          # Warning 60 seconds before game starts
  announcement:
    enabled: true
    start-message: "&aChickenHunt game in region %region% will start in %seconds% seconds!"
    started-message: "&aChickenHunt game in region %region% has started for %minutes% minutes!"
    end-message: "&eChickenHunt game in region %region% has ended!"

# Tiered Reward System
rewards:
  tier-rewards:
    enabled: true
    message: "&a&lCONGRATULATIONS! &eYou have received a reward for catching &6%count% &echickens!"
    tiers:
      - count: 10
        commands:
          - "give %player% minecraft:diamond 1"
          - "title %player% subtitle \"&eGiven 1 Diamond\""
      - count: 25
        commands:
          - "give %player% minecraft:emerald 3"
          - "title %player% subtitle \"&eGiven 3 Emeralds\""
      - count: 50
        commands:
          - "give %player% minecraft:netherite_ingot 1"
          - "title %player% subtitle \"&eGiven 1 Netherite Ingot\""
      - count: 100
        commands:
          - "give %player% minecraft:diamond_block 1"
          - "give %player% minecraft:emerald_block 1"
          - "broadcast &6%player% &ehas become a legendary hunter with 100 chicken catches!"